"""Shared factory for syntax-only TextAreaThemes. No background — terminal shows through."""

from __future__ import annotations

from rich.style import Style
from textual.widgets.text_area import TextAreaTheme


def build(
    name: str,
    *,
    fg: str,
    comment: str,
    keyword: str,
    string: str,
    func: str,
    number: str,
    type_: str,
    builtin: str,
    operator: str,
    punct: str,
    selection: str,
    gutter: str,
    gutter_hl: str,
    decorator: str,
    escape: str,
    param: str,
    attr: str,
    constant: str,
    regexp: str,
) -> TextAreaTheme:
    return TextAreaTheme(
        name=name,
        base_style=Style(color=fg),
        gutter_style=Style(color=gutter),
        cursor_style=Style(),
        cursor_line_style=Style(),
        cursor_line_gutter_style=Style(color=gutter_hl),
        bracket_matching_style=Style(color=fg, underline=True),
        selection_style=Style(bgcolor=selection),
        syntax_styles={
            "string": Style(color=string),
            "string.documentation": Style(color=string, italic=True),
            "string.escape": Style(color=escape),
            "string.special": Style(color=escape),
            "string.regexp": Style(color=regexp, italic=True),
            "escape": Style(color=escape),
            "embedded": Style(color=escape),
            "comment": Style(color=comment, italic=True),
            "comment.documentation": Style(color=comment, italic=True),
            "keyword": Style(color=keyword),
            "keyword.function": Style(color=keyword),
            "keyword.return": Style(color=keyword),
            "keyword.operator": Style(color=keyword),
            "conditional": Style(color=keyword),
            "repeat": Style(color=keyword),
            "exception": Style(color=keyword),
            "include": Style(color=keyword),
            "operator": Style(color=operator),
            "punctuation.bracket": Style(color=punct),
            "punctuation.delimiter": Style(color=punct),
            "punctuation.special": Style(color=punct),
            "number": Style(color=number),
            "float": Style(color=number),
            "boolean": Style(color=builtin, italic=True),
            "constant": Style(color=constant),
            "constant.builtin": Style(color=builtin, italic=True),
            "constant.macro": Style(color=decorator),
            "variable": Style(color=fg),
            "variable.builtin": Style(color=builtin, italic=True),
            "variable.parameter": Style(color=param),
            "parameter": Style(color=param),
            "field": Style(color=attr),
            "type": Style(color=type_),
            "type.builtin": Style(color=type_, italic=True),
            "type.class": Style(color=type_),
            "type.definition": Style(color=type_),
            "type.parameter": Style(color=type_, italic=True),
            "class": Style(color=type_),
            "constructor": Style(color=type_),
            "function": Style(color=func),
            "function.call": Style(color=func),
            "function.builtin": Style(color=builtin),
            "function.macro": Style(color=decorator),
            "function.method": Style(color=func),
            "method": Style(color=func),
            "method.call": Style(color=func),
            "attribute": Style(color=decorator),
            "attribute.builtin": Style(color=decorator),
            "decorator": Style(color=decorator),
            "property": Style(color=attr),
            "label": Style(color=comment),
            "character": Style(color=string),
            "tag": Style(color=keyword),
            "json.label": Style(color=keyword),
            "yaml.field": Style(color=keyword),
            "heading": Style(color=keyword, bold=True),
            "bold": Style(bold=True),
            "italic": Style(italic=True),
            "link.uri": Style(color=type_, underline=True),
            "inline_code": Style(color=string),
        },
    )
